replicaCount: 1
image:
  tag: latest
ingress:
  enabled: "true"
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: staging.aisapi.com.tr
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []