apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cicd-sample-app-production
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/T1kcan/sample-app-gitops.git
    targetRevision: main
    path: charts/sample-app
    helm:
      valueFiles:
        - ../../environments/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true