replicaCount: 2
image:
  tag: 
ingress:
  enabled: "true"
  className: "nginx"
  annotations: 
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: 
      paths:jenkins.aisapi.com.tr
        - path: /
          pathType: ImplementationSpecific
  tls: []